version: '2.1'
name: player-metric-service
services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB:       "saop_prod"
      POSTGRES_HOST_AUTH_METHOD: trust 
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  configserver:
    image: saop/configserver:0.0.1-SNAPSHOT
    ports:
       - "8071:8071"
    networks:
      backend:
        aliases:
          - "configserver"
  playermetricservice:
    image: saop/playermetricservice:0.0.2-SNAPSHOT
    environment:
      PROFILE: "prod"
      CONFIGSERVER_URI: "http://configserver:8071"
      CONFIGSERVER_PORT:   "8071"
      DATABASESERVER_PORT: "5432"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - backend
  
networks:
  backend:
    driver: bridge